import { ref, computed } from 'vue'
import { loadSettings, saveSettings } from '../api/tauri'

/**
 * 图标集接口定义
 */
export interface IconSet {
  id: string
  name: string
  description: string
  type: 'emoji' | 'svg'
  icons: {
    folder: {
      closed: string
      open: string
    }
    files: Record<string, string>
  }
}

/**
 * 预定义图标集
 */
export const iconSets: IconSet[] = [
  {
    id: 'emoji',
    name: 'Emoji 图标',
    description: '使用 Emoji 字符作为文件图标',
    type: 'emoji',
    icons: {
      folder: {
        closed: '📁',
        open: '📂'
      },
      files: {
        'json': '📄',
        'js': '📜',
        'ts': '📜',
        'vue': '💚',
        'css': '🎨',
        'scss': '🎨',
        'sass': '🎨',
        'less': '🎨',
        'png': '🖼️',
        'jpg': '🖼️',
        'jpeg': '🖼️',
        'gif': '🖼️',
        'svg': '🖼️',
        'txt': '📝',
        'md': '📝',
        'mod': '⚙️',
        'gui': '🖥️',
        'event': '📅',
        'focus': '🎯',
        'idea': '💡',
        'on_action': '⚡',
        'decision': '🔀',
        'default': '📄'
      }
    }
  },
  {
    id: 'material',
    name: 'Material Icons',
    description: 'Google Material Design 风格图标',
    type: 'svg',
    icons: {
      folder: {
        closed: '/icon/iconSystem/vscode/folder.svg',
        open: '/icon/iconSystem/vscode/folder.svg'
      },
      files: {
        // 编程语言
        'js': '/icon/iconSystem/material/javascript.svg',
        'jsx': '/icon/iconSystem/material/javascript.svg',
        'ts': '/icon/iconSystem/material/typescript.svg',
        'tsx': '/icon/iconSystem/material/typescript.svg',
        'vue': '/icon/iconSystem/material/vue.svg',
        'html': '/icon/iconSystem/material/html.svg',
        'css': '/icon/iconSystem/material/css.svg',
        'scss': '/icon/iconSystem/material/css.svg',
        'sass': '/icon/iconSystem/material/css.svg',
        'less': '/icon/iconSystem/material/css.svg',
        'json': '/icon/iconSystem/material/json.svg',
        'xml': '/icon/iconSystem/material/xml.svg',
        'yaml': '/icon/iconSystem/material/yaml.svg',
        'yml': '/icon/iconSystem/material/yaml.svg',
        'toml': '/icon/iconSystem/material/toml.svg',
        'py': '/icon/iconSystem/material/python.svg',
        'java': '/icon/iconSystem/material/java.svg',
        'c': '/icon/iconSystem/material/c.svg',
        'cpp': '/icon/iconSystem/material/cpp.svg',
        'cs': '/icon/iconSystem/material/csharp.svg',
        'php': '/icon/iconSystem/material/php.svg',
        'rb': '/icon/iconSystem/material/ruby.svg',
        'go': '/icon/iconSystem/material/go.svg',
        'rs': '/icon/iconSystem/material/rust.svg',
        'swift': '/icon/iconSystem/material/swift.svg',
        'kt': '/icon/iconSystem/material/kotlin.svg',
        'scala': '/icon/iconSystem/material/scala.svg',
        'clj': '/icon/iconSystem/material/clojure.svg',
        'hs': '/icon/iconSystem/material/haskell.svg',
        'ml': '/icon/iconSystem/material/ocaml.svg',
        'elm': '/icon/iconSystem/material/elm.svg',
        'dart': '/icon/iconSystem/material/dart.svg',
        'lua': '/icon/iconSystem/material/lua.svg',
        'pl': '/icon/iconSystem/material/perl.svg',
        'r': '/icon/iconSystem/material/r.svg',
        'm': '/icon/iconSystem/material/matlab.svg',
        'sh': '/icon/iconSystem/material/shell.svg',
        'bash': '/icon/iconSystem/material/shell.svg',
        'zsh': '/icon/iconSystem/material/shell.svg',
        'fish': '/icon/iconSystem/material/shell.svg',
        'ps1': '/icon/iconSystem/material/powershell.svg',
        'bat': '/icon/iconSystem/material/powershell.svg',
        'cmd': '/icon/iconSystem/material/powershell.svg',
        'sql': '/icon/iconSystem/material/database.svg',
        'dockerfile': '/icon/iconSystem/material/docker.svg',
        'makefile': '/icon/iconSystem/material/makefile.svg',
        'cmake': '/icon/iconSystem/material/cmake.svg',
        'gradle': '/icon/iconSystem/material/gradle.svg',
        'maven': '/icon/iconSystem/material/maven.svg',
        'sbt': '/icon/iconSystem/material/sbt.svg',
        'cabal': '/icon/iconSystem/material/cabal.svg',
        'gemfile': '/icon/iconSystem/material/ruby.svg',
        'package': '/icon/iconSystem/material/npm.svg',
        'lock': '/icon/iconSystem/material/lock.svg',
        'gitignore': '/icon/iconSystem/vscode/git_ignore.svg',
        'gitattributes': '/icon/iconSystem/vscode/git.svg',
        'gitmodules': '/icon/iconSystem/vscode/git.svg',
        'editorconfig': '/icon/iconSystem/vscode/editorconfig.svg',
        'eslintrc': '/icon/iconSystem/vscode/eslint.svg',
        'prettierrc': '/icon/iconSystem/material/prettier.svg',
        'babelrc': '/icon/iconSystem/material/babel.svg',
        'tsconfig': '/icon/iconSystem/vscode/tsconfig.svg',
        'webpack': '/icon/iconSystem/material/webpack.svg',
        'rollup': '/icon/iconSystem/material/rollup.svg',
        'vite': '/icon/iconSystem/material/vite.svg',
        'parcel': '/icon/iconSystem/material/parcel.svg',
        'next': '/icon/iconSystem/material/next.svg',
        'nuxt': '/icon/iconSystem/material/nuxt.svg',
        'gatsby': '/icon/iconSystem/material/gatsby.svg',
        'svelte': '/icon/iconSystem/material/svelte.svg',
        'astro': '/icon/iconSystem/material/astro.svg',
        'solid': '/icon/iconSystem/material/react.svg',
        'remix': '/icon/iconSystem/material/remix.svg',
        'angular': '/icon/iconSystem/material/angular.svg',
        'react': '/icon/iconSystem/material/react.svg',
        'redux': '/icon/iconSystem/material/redux-store.svg',
        'vuepress': '/icon/iconSystem/material/vue.svg',
        'quasar': '/icon/iconSystem/material/quasar.svg',
        'ionic': '/icon/iconSystem/material/ionic.svg',
        'expo': '/icon/iconSystem/material/react.svg',
        'flutter': '/icon/iconSystem/material/flutter.svg',
        'android': '/icon/iconSystem/material/android.svg',
        'ios': '/icon/iconSystem/material/apple.svg',
        'tauri': '/icon/iconSystem/material/tauri.svg',
        'electron': '/icon/iconSystem/material/electron.svg',
        'node': '/icon/iconSystem/material/nodejs.svg',
        'npm': '/icon/iconSystem/material/npm.svg',
        'yarn': '/icon/iconSystem/material/yarn.svg',
        'pnpm': '/icon/iconSystem/material/pnpm.svg',
        'bun': '/icon/iconSystem/material/bun.svg',
        'pip': '/icon/iconSystem/material/python.svg',
        'conda': '/icon/iconSystem/material/python.svg',
        'poetry': '/icon/iconSystem/material/poetry.svg',
        'composer': '/icon/iconSystem/material/php.svg',
        'log': '/icon/iconSystem/material/log.svg',
        'env': '/icon/iconSystem/material/settings.svg',
        'config': '/icon/iconSystem/material/settings.svg',
        'conf': '/icon/iconSystem/material/settings.svg',
        'ini': '/icon/iconSystem/material/settings.svg',
        'cfg': '/icon/iconSystem/material/settings.svg',
        'plist': '/icon/iconSystem/material/settings.svg',
        'properties': '/icon/iconSystem/material/settings.svg',
        'theme': '/icon/iconSystem/material/palette.svg',
        'txt': '/icon/iconSystem/material/document.svg',
        'md': '/icon/iconSystem/material/markdown.svg',
        'markdown': '/icon/iconSystem/material/markdown.svg',
        'rst': '/icon/iconSystem/material/document.svg',
        'adoc': '/icon/iconSystem/material/asciidoc.svg',
        'tex': '/icon/iconSystem/material/tex.svg',
        'bib': '/icon/iconSystem/material/bibliography.svg',
        'pdf': '/icon/iconSystem/material/pdf.svg',
        'doc': '/icon/iconSystem/material/word.svg',
        'docx': '/icon/iconSystem/material/word.svg',
        'xls': '/icon/iconSystem/material/excel.svg',
        'xlsx': '/icon/iconSystem/material/excel.svg',
        'ppt': '/icon/iconSystem/material/powerpoint.svg',
        'pptx': '/icon/iconSystem/material/powerpoint.svg',
        'odt': '/icon/iconSystem/material/document.svg',
        'ods': '/icon/iconSystem/material/excel.svg',
        'odp': '/icon/iconSystem/material/powerpoint.svg',
        'png': '/icon/iconSystem/material/image.svg',
        'dds': '/icon/iconSystem/material/image.svg',
        'tga': '/icon/iconSystem/material/image.svg',
        'gfx': '/icon/iconSystem/material/image.svg',
        'jpg': '/icon/iconSystem/material/image.svg',
        'jpeg': '/icon/iconSystem/material/image.svg',
        'gif': '/icon/iconSystem/material/image.svg',
        'svg': '/icon/iconSystem/material/svg.svg',
        'ico': '/icon/iconSystem/material/image.svg',
        'bmp': '/icon/iconSystem/material/image.svg',
        'tiff': '/icon/iconSystem/material/image.svg',
        'webp': '/icon/iconSystem/material/image.svg',
        'mp3': '/icon/iconSystem/material/audio.svg',
        'wav': '/icon/iconSystem/material/audio.svg',
        'flac': '/icon/iconSystem/material/audio.svg',
        'ogg': '/icon/iconSystem/material/audio.svg',
        'm4a': '/icon/iconSystem/material/audio.svg',
        'mp4': '/icon/iconSystem/material/video.svg',
        'avi': '/icon/iconSystem/material/video.svg',
        'mkv': '/icon/iconSystem/material/video.svg',
        'mov': '/icon/iconSystem/material/video.svg',
        'wmv': '/icon/iconSystem/material/video.svg',
        'flv': '/icon/iconSystem/material/video.svg',
        'webm': '/icon/iconSystem/material/video.svg',
        'zip': '/icon/iconSystem/material/zip.svg',
        'rar': '/icon/iconSystem/material/zip.svg',
        '7z': '/icon/iconSystem/material/zip.svg',
        'tar': '/icon/iconSystem/material/zip.svg',
        'gz': '/icon/iconSystem/material/zip.svg',
        'bz2': '/icon/iconSystem/material/zip.svg',
        'xz': '/icon/iconSystem/material/zip.svg',
        'exe': '/icon/iconSystem/material/executable.svg',
        'msi': '/icon/iconSystem/material/executable.svg',
        'deb': '/icon/iconSystem/material/executable.svg',
        'rpm': '/icon/iconSystem/material/executable.svg',
        'dmg': '/icon/iconSystem/material/executable.svg',
        'pkg': '/icon/iconSystem/material/executable.svg',
        'appimage': '/icon/iconSystem/material/executable.svg',
        'snap': '/icon/iconSystem/material/executable.svg',
        'flatpak': '/icon/iconSystem/material/executable.svg',
        'iso': '/icon/iconSystem/material/executable.svg',
        'img': '/icon/iconSystem/material/executable.svg',
        'vhd': '/icon/iconSystem/material/executable.svg',
        'vmdk': '/icon/iconSystem/material/executable.svg',
        'ova': '/icon/iconSystem/material/executable.svg',
        'ovf': '/icon/iconSystem/material/executable.svg',
        'cert': '/icon/iconSystem/material/certificate.svg',
        'crt': '/icon/iconSystem/material/certificate.svg',
        'key': '/icon/iconSystem/material/certificate.svg',
        'pem': '/icon/iconSystem/material/certificate.svg',
        'p12': '/icon/iconSystem/material/certificate.svg',
        'pfx': '/icon/iconSystem/material/certificate.svg',
        'crl': '/icon/iconSystem/material/certificate.svg',
        'der': '/icon/iconSystem/material/certificate.svg',
        'csr': '/icon/iconSystem/material/certificate.svg',
        'pub': '/icon/iconSystem/material/certificate.svg',
        'sig': '/icon/iconSystem/material/certificate.svg',
        'asc': '/icon/iconSystem/material/certificate.svg',
        'gpg': '/icon/iconSystem/material/certificate.svg',
        'license': '/icon/iconSystem/material/license.svg',
        'licence': '/icon/iconSystem/material/license.svg',
        'copying': '/icon/iconSystem/material/license.svg',
        'unlicense': '/icon/iconSystem/material/unlicense.svg',
        'mit': '/icon/iconSystem/material/license.svg',
        'gpl': '/icon/iconSystem/material/license.svg',
        'apache': '/icon/iconSystem/material/license.svg',
        'bsd': '/icon/iconSystem/material/license.svg',
        'mpl': '/icon/iconSystem/material/license.svg',
        'lgpl': '/icon/iconSystem/material/license.svg',
        'agpl': '/icon/iconSystem/material/license.svg',
        'epl': '/icon/iconSystem/material/license.svg',
        'afl': '/icon/iconSystem/material/license.svg',
        'cc0': '/icon/iconSystem/material/license.svg',
        'ccby': '/icon/iconSystem/material/license.svg',
        'ccbysa': '/icon/iconSystem/material/license.svg',
        'ccbynd': '/icon/iconSystem/material/license.svg',
        'ccbync': '/icon/iconSystem/material/license.svg',
        'ccbyncsa': '/icon/iconSystem/material/license.svg',
        'ccbyncnd': '/icon/iconSystem/material/license.svg',
        'gfdl': '/icon/iconSystem/material/license.svg',
        'odbl': '/icon/iconSystem/material/license.svg',
        'ofl': '/icon/iconSystem/material/license.svg',
        'osl': '/icon/iconSystem/material/license.svg',
        'postgresql': '/icon/iconSystem/material/database.svg',
        'mysql': '/icon/iconSystem/material/database.svg',
        'sqlite': '/icon/iconSystem/material/database.svg',
        'mongodb': '/icon/iconSystem/material/database.svg',
        'redis': '/icon/iconSystem/material/database.svg',
        'elasticsearch': '/icon/iconSystem/material/database.svg',
        'kibana': '/icon/iconSystem/material/database.svg',
        'logstash': '/icon/iconSystem/material/database.svg',
        'grafana': '/icon/iconSystem/material/database.svg',
        'prometheus': '/icon/iconSystem/material/database.svg',
        'kubernetes': '/icon/iconSystem/material/kubernetes.svg',
        'docker': '/icon/iconSystem/material/docker.svg',
        'terraform': '/icon/iconSystem/material/terraform.svg',
        'ansible': '/icon/iconSystem/material/ansible.svg',
        'puppet': '/icon/iconSystem/material/puppet.svg',
        'chef': '/icon/iconSystem/material/chef.svg',
        'vagrant': '/icon/iconSystem/material/vagrant.svg',
        'jenkins': '/icon/iconSystem/material/jenkins.svg',
        'gitlab': '/icon/iconSystem/material/gitlab.svg',
        'github': '/icon/iconSystem/material/github.svg',
        'bitbucket': '/icon/iconSystem/material/bitbucket.svg',
        'azure': '/icon/iconSystem/material/azure.svg',
        'aws': '/icon/iconSystem/material/aws.svg',
        'gcp': '/icon/iconSystem/material/google.svg',
        'firebase': '/icon/iconSystem/material/firebase.svg',
        'heroku': '/icon/iconSystem/material/heroku.svg',
        'netlify': '/icon/iconSystem/material/netlify.svg',
        'vercel': '/icon/iconSystem/material/vercel.svg',
        'railway': '/icon/iconSystem/material/railway.svg',
        'render': '/icon/iconSystem/material/render.svg',
        'digitalocean': '/icon/iconSystem/material/digitalocean.svg',
        'cloudflare': '/icon/iconSystem/material/cloudflare.svg',
        'nginx': '/icon/iconSystem/material/nginx.svg',
        'caddy': '/icon/iconSystem/material/caddy.svg',
        'traefik': '/icon/iconSystem/material/traefik.svg',
        'haproxy': '/icon/iconSystem/material/haproxy.svg',
        'envoy': '/icon/iconSystem/material/envoy.svg',
        'istio': '/icon/iconSystem/material/istio.svg',
        'linkerd': '/icon/iconSystem/material/linkerd.svg',
        'consul': '/icon/iconSystem/material/consul.svg',
        'vault': '/icon/iconSystem/material/vault.svg',
        'nomad': '/icon/iconSystem/material/nomad.svg',
        'etcd': '/icon/iconSystem/material/etcd.svg',
        'zookeeper': '/icon/iconSystem/material/zookeeper.svg',
        'kafka': '/icon/iconSystem/material/kafka.svg',
        'rabbitmq': '/icon/iconSystem/material/rabbitmq.svg',
        'nats': '/icon/iconSystem/material/nats.svg',
        'pulsar': '/icon/iconSystem/material/pulsar.svg',
        'activemq': '/icon/iconSystem/material/activemq.svg',
        'zeromq': '/icon/iconSystem/material/zeromq.svg',
        'mosquitto': '/icon/iconSystem/material/mosquitto.svg',
        'emqx': '/icon/iconSystem/material/emqx.svg',
        'hivemq': '/icon/iconSystem/material/hivemq.svg',
        'vernemq': '/icon/iconSystem/material/vernemq.svg',
        'solace': '/icon/iconSystem/material/solace.svg',
        'tibco': '/icon/iconSystem/material/tibco.svg',
        'ibmmq': '/icon/iconSystem/material/ibmmq.svg',
        'graphql': '/icon/iconSystem/material/graphql.svg',
        'protobuf': '/icon/iconSystem/material/protobuf.svg',
        'thrift': '/icon/iconSystem/material/thrift.svg',
        'avro': '/icon/iconSystem/material/avro.svg',
        'openapi': '/icon/iconSystem/material/openapi.svg',
        'swagger': '/icon/iconSystem/material/swagger.svg',
        'raml': '/icon/iconSystem/material/raml.svg',
        'api': '/icon/iconSystem/material/api.svg',
        'postman': '/icon/iconSystem/material/postman.svg',
        'insomnia': '/icon/iconSystem/material/insomnia.svg',
        'hoppscotch': '/icon/iconSystem/material/hoppscotch.svg',
        'soapui': '/icon/iconSystem/material/soapui.svg',
        'jmeter': '/icon/iconSystem/material/jmeter.svg',
        'k6': '/icon/iconSystem/material/k6.svg',
        'artillery': '/icon/iconSystem/material/artillery.svg',
        'locust': '/icon/iconSystem/material/locust.svg',
        'gatling': '/icon/iconSystem/material/gatling.svg',
        'tsung': '/icon/iconSystem/material/tsung.svg',
        'wrk': '/icon/iconSystem/material/wrk.svg',
        'hey': '/icon/iconSystem/material/hey.svg',
        'ab': '/icon/iconSystem/material/ab.svg',
        'siege': '/icon/iconSystem/material/siege.svg',
        'beeswithmachineguns': '/icon/iconSystem/material/beeswithmachineguns.svg',
        'boom': '/icon/iconSystem/material/boom.svg',
        'autocannon': '/icon/iconSystem/material/autocannon.svg',
        'bombardier': '/icon/iconSystem/material/bombardier.svg',
        'vegeta': '/icon/iconSystem/material/vegeta.svg',
        'fortio': '/icon/iconSystem/material/fortio.svg',
        'wrk2': '/icon/iconSystem/material/wrk2.svg',
        'oha': '/icon/iconSystem/material/oha.svg',
        'httpie': '/icon/iconSystem/material/httpie.svg',
        'curl': '/icon/iconSystem/material/curl.svg',
        'wget': '/icon/iconSystem/material/wget.svg',
        'aria2': '/icon/iconSystem/material/aria2.svg',
        'youtube-dl': '/icon/iconSystem/material/youtube-dl.svg',
        'yt-dlp': '/icon/iconSystem/material/yt-dlp.svg',
        'gallery-dl': '/icon/iconSystem/material/gallery-dl.svg',
        'instaloader': '/icon/iconSystem/material/instaloader.svg',
        'twitter-dl': '/icon/iconSystem/material/twitter-dl.svg',
        'reddit-dl': '/icon/iconSystem/material/reddit-dl.svg',
        'instagram-dl': '/icon/iconSystem/material/instagram-dl.svg',
        'tiktok-dl': '/icon/iconSystem/material/tiktok-dl.svg',
        'spotify-dl': '/icon/iconSystem/material/spotify-dl.svg',
        'soundcloud-dl': '/icon/iconSystem/material/soundcloud-dl.svg',
        'bandcamp-dl': '/icon/iconSystem/material/bandcamp-dl.svg',
        'mixcloud-dl': '/icon/iconSystem/material/mixcloud-dl.svg',
        'twitch-dl': '/icon/iconSystem/material/twitch-dl.svg',
        'vimeo-dl': '/icon/iconSystem/material/vimeo-dl.svg',
        'dailymotion-dl': '/icon/iconSystem/material/dailymotion-dl.svg',
        'bilibili-dl': '/icon/iconSystem/material/bilibili-dl.svg',
        'youku-dl': '/icon/iconSystem/material/youku-dl.svg',
        'iqiyi-dl': '/icon/iconSystem/material/iqiyi-dl.svg',
        'tudou-dl': '/icon/iconSystem/material/tudou-dl.svg',
        'letv-dl': '/icon/iconSystem/material/letv-dl.svg',
        'sohu-dl': '/icon/iconSystem/material/sohu-dl.svg',
        'qq-dl': '/icon/iconSystem/material/qq-dl.svg',
        '163-dl': '/icon/iconSystem/material/163-dl.svg',
        '56-dl': '/icon/iconSystem/material/56-dl.svg',
        'kugou-dl': '/icon/iconSystem/material/kugou-dl.svg',
        'kuwo-dl': '/icon/iconSystem/material/kuwo-dl.svg',
        '9ku-dl': '/icon/iconSystem/material/9ku-dl.svg',
        '1ting-dl': '/icon/iconSystem/material/1ting-dl.svg',
        'migu-dl': '/icon/iconSystem/material/migu-dl.svg',
        'joox-dl': '/icon/iconSystem/material/joox-dl.svg',
        'qqmusic-dl': '/icon/iconSystem/material/qqmusic-dl.svg',
        'netease-dl': '/icon/iconSystem/material/netease-dl.svg',
        'xiami-dl': '/icon/iconSystem/material/xiami-dl.svg',
        'baidu-dl': '/icon/iconSystem/material/baidu-dl.svg',
        'google-dl': '/icon/iconSystem/material/google-dl.svg',
        'bing-dl': '/icon/iconSystem/material/bing-dl.svg',
        'yahoo-dl': '/icon/iconSystem/material/yahoo-dl.svg',
        'duckduckgo-dl': '/icon/iconSystem/material/duckduckgo-dl.svg',
        'sogou-dl': '/icon/iconSystem/material/sogou-dl.svg',
        '360-dl': '/icon/iconSystem/material/360-dl.svg',
        'startpage-dl': '/icon/iconSystem/material/startpage-dl.svg',
        'yandex-dl': '/icon/iconSystem/material/yandex-dl.svg',
        'naver-dl': '/icon/iconSystem/material/naver-dl.svg',
        'daum-dl': '/icon/iconSystem/material/daum-dl.svg',
        'nate-dl': '/icon/iconSystem/material/nate-dl.svg',
        'zum-dl': '/icon/iconSystem/material/zum-dl.svg',
        'eniro-dl': '/icon/iconSystem/material/eniro-dl.svg',
        'ekolay-dl': '/icon/iconSystem/material/ekolay-dl.svg',
        'yam-dl': '/icon/iconSystem/material/yam-dl.svg',
        'mod': '/icon/iconSystem/vscode/config.svg',
        'gui': '/icon/iconSystem/vscode/config.svg',
        'event': '/icon/iconSystem/vscode/default.svg',
        'focus': '/icon/iconSystem/vscode/default.svg',
        'idea': '/icon/iconSystem/vscode/default.svg',
        'on_action': '/icon/iconSystem/vscode/default.svg',
        'decision': '/icon/iconSystem/vscode/default.svg',
        'default': '/icon/iconSystem/material/document.svg'
      }
    }
  },
  {
    id: 'vscode',
    name: 'VS Code 风格',
    description: '模仿 VS Code 的文件图标风格',
    type: 'svg',
    icons: {
      folder: {
        closed: '/icon/iconSystem/vscode/folder.svg',
        open: '/icon/iconSystem/vscode/folder.svg'
      },
      files: {
        // 编程语言
        'js': '/icon/iconSystem/vscode/javascript.svg',
        'jsx': '/icon/iconSystem/vscode/javascript.svg',
        'ts': '/icon/iconSystem/vscode/typescript.svg',
        'tsx': '/icon/iconSystem/vscode/typescript.svg',
        'vue': '/icon/iconSystem/vscode/vue.svg',
        'html': '/icon/iconSystem/vscode/html.svg',
        'css': '/icon/iconSystem/vscode/css.svg',
        'scss': '/icon/iconSystem/vscode/sass.svg',
        'sass': '/icon/iconSystem/vscode/sass.svg',
        'less': '/icon/iconSystem/vscode/less.svg',
        'json': '/icon/iconSystem/vscode/json.svg',
        'xml': '/icon/iconSystem/vscode/xml.svg',
        'yaml': '/icon/iconSystem/vscode/yml.svg',
        'yml': '/icon/iconSystem/vscode/yml.svg',
        'toml': '/icon/iconSystem/vscode/yml.svg',
        'py': '/icon/iconSystem/vscode/python.svg',
        'java': '/icon/iconSystem/vscode/java.svg',
        'c': '/icon/iconSystem/vscode/c.svg',
        'cpp': '/icon/iconSystem/vscode/cpp.svg',
        'cs': '/icon/iconSystem/vscode/c-sharp.svg',
        'php': '/icon/iconSystem/vscode/php.svg',
        'rb': '/icon/iconSystem/vscode/ruby.svg',
        'go': '/icon/iconSystem/vscode/go.svg',
        'rs': '/icon/iconSystem/vscode/rust.svg',
        'swift': '/icon/iconSystem/vscode/swift.svg',
        'kt': '/icon/iconSystem/vscode/kotlin.svg',
        'scala': '/icon/iconSystem/vscode/scala.svg',
        'clj': '/icon/iconSystem/vscode/clojure.svg',
        'hs': '/icon/iconSystem/vscode/haskell.svg',
        'ml': '/icon/iconSystem/vscode/ocaml.svg',
        'elm': '/icon/iconSystem/vscode/elm.svg',
        'dart': '/icon/iconSystem/vscode/dart.svg',
        'lua': '/icon/iconSystem/vscode/lua.svg',
        'pl': '/icon/iconSystem/vscode/perl.svg',
        'r': '/icon/iconSystem/vscode/R.svg',
        'sh': '/icon/iconSystem/vscode/shell.svg',
        'bash': '/icon/iconSystem/vscode/shell.svg',
        'zsh': '/icon/iconSystem/vscode/shell.svg',
        'fish': '/icon/iconSystem/vscode/shell.svg',
        'ps1': '/icon/iconSystem/vscode/powershell.svg',
        'bat': '/icon/iconSystem/vscode/powershell.svg',
        'cmd': '/icon/iconSystem/vscode/powershell.svg',
        'sql': '/icon/iconSystem/vscode/db.svg',
        'dockerfile': '/icon/iconSystem/vscode/docker.svg',
        'makefile': '/icon/iconSystem/vscode/makefile.svg',
        'cmake': '/icon/iconSystem/vscode/cmake.svg',
        'gradle': '/icon/iconSystem/vscode/gradle.svg',
        'maven': '/icon/iconSystem/vscode/maven.svg',
        'sbt': '/icon/iconSystem/vscode/sbt.svg',
        'gemfile': '/icon/iconSystem/vscode/ruby.svg',
        'package': '/icon/iconSystem/vscode/npm.svg',
        'lock': '/icon/iconSystem/vscode/lock.svg',
        'gitignore': '/icon/iconSystem/vscode/git_ignore.svg',
        'gitattributes': '/icon/iconSystem/vscode/git.svg',
        'gitmodules': '/icon/iconSystem/vscode/git.svg',
        'editorconfig': '/icon/iconSystem/vscode/editorconfig.svg',
        'eslintrc': '/icon/iconSystem/vscode/eslint.svg',
        'prettierrc': '/icon/iconSystem/vscode/prettier.svg',
        'babelrc': '/icon/iconSystem/vscode/babel.svg',
        'tsconfig': '/icon/iconSystem/vscode/tsconfig.svg',
        'webpack': '/icon/iconSystem/vscode/webpack.svg',
        'rollup': '/icon/iconSystem/vscode/rollup.svg',
        'vite': '/icon/iconSystem/vscode/vite.svg',
        'parcel': '/icon/iconSystem/vscode/parcel.svg',
        'next': '/icon/iconSystem/vscode/next.svg',
        'nuxt': '/icon/iconSystem/vscode/nuxt.svg',
        'gatsby': '/icon/iconSystem/vscode/gatsby.svg',
        'svelte': '/icon/iconSystem/vscode/svelte.svg',
        'astro': '/icon/iconSystem/vscode/astro.svg',
        'solid': '/icon/iconSystem/vscode/react.svg',
        'remix': '/icon/iconSystem/vscode/remix.svg',
        'angular': '/icon/iconSystem/vscode/angular.svg',
        'react': '/icon/iconSystem/vscode/react.svg',
        'redux': '/icon/iconSystem/vscode/react.svg',
        'vuepress': '/icon/iconSystem/vscode/vue.svg',
        'quasar': '/icon/iconSystem/vscode/quasar.svg',
        'ionic': '/icon/iconSystem/vscode/ionic.svg',
        'expo': '/icon/iconSystem/vscode/react.svg',
        'flutter': '/icon/iconSystem/vscode/flutter.svg',
        'android': '/icon/iconSystem/vscode/android.svg',
        'ios': '/icon/iconSystem/vscode/apple.svg',
        'tauri': '/icon/iconSystem/vscode/rust.svg',
        'electron': '/icon/iconSystem/vscode/javascript.svg',
        'node': '/icon/iconSystem/vscode/javascript.svg',
        'npm': '/icon/iconSystem/vscode/npm.svg',
        'yarn': '/icon/iconSystem/vscode/yarn.svg',
        'pnpm': '/icon/iconSystem/vscode/npm.svg',
        'bun': '/icon/iconSystem/vscode/javascript.svg',
        'pip': '/icon/iconSystem/vscode/python.svg',
        'conda': '/icon/iconSystem/vscode/python.svg',
        'poetry': '/icon/iconSystem/vscode/python.svg',
        'composer': '/icon/iconSystem/vscode/php.svg',
        'log': '/icon/iconSystem/vscode/default.svg',
        'env': '/icon/iconSystem/vscode/config.svg',
        'config': '/icon/iconSystem/vscode/config.svg',
        'conf': '/icon/iconSystem/vscode/config.svg',
        'ini': '/icon/iconSystem/vscode/config.svg',
        'cfg': '/icon/iconSystem/vscode/config.svg',
        'plist': '/icon/iconSystem/vscode/config.svg',
        'properties': '/icon/iconSystem/vscode/config.svg',
        'theme': '/icon/iconSystem/vscode/palette.svg',
        'txt': '/icon/iconSystem/material/document.svg',
        'md': '/icon/iconSystem/vscode/markdown.svg',
        'markdown': '/icon/iconSystem/vscode/markdown.svg',
        'rst': '/icon/iconSystem/vscode/default.svg',
        'adoc': '/icon/iconSystem/vscode/default.svg',
        'tex': '/icon/iconSystem/vscode/tex.svg',
        'bib': '/icon/iconSystem/vscode/default.svg',
        'pdf': '/icon/iconSystem/vscode/pdf.svg',
        'doc': '/icon/iconSystem/vscode/word.svg',
        'docx': '/icon/iconSystem/vscode/word.svg',
        'xls': '/icon/iconSystem/vscode/xls.svg',
        'xlsx': '/icon/iconSystem/vscode/xls.svg',
        'ppt': '/icon/iconSystem/vscode/default.svg',
        'pptx': '/icon/iconSystem/vscode/default.svg',
        'odt': '/icon/iconSystem/vscode/default.svg',
        'ods': '/icon/iconSystem/vscode/xls.svg',
        'odp': '/icon/iconSystem/vscode/default.svg',
        'png': '/icon/iconSystem/vscode/image.svg',
        'jpg': '/icon/iconSystem/vscode/image.svg',
        'jpeg': '/icon/iconSystem/vscode/image.svg',
        'gif': '/icon/iconSystem/vscode/image.svg',
        'svg': '/icon/iconSystem/vscode/svg.svg',
        'ico': '/icon/iconSystem/vscode/favicon.svg',
        'bmp': '/icon/iconSystem/vscode/image.svg',
        'tiff': '/icon/iconSystem/vscode/image.svg',
        'webp': '/icon/iconSystem/vscode/image.svg',
        'mp3': '/icon/iconSystem/vscode/audio.svg',
        'wav': '/icon/iconSystem/vscode/audio.svg',
        'flac': '/icon/iconSystem/vscode/audio.svg',
        'ogg': '/icon/iconSystem/vscode/audio.svg',
        'm4a': '/icon/iconSystem/vscode/audio.svg',
        'mp4': '/icon/iconSystem/vscode/video.svg',
        'avi': '/icon/iconSystem/vscode/video.svg',
        'mkv': '/icon/iconSystem/vscode/video.svg',
        'mov': '/icon/iconSystem/vscode/video.svg',
        'wmv': '/icon/iconSystem/vscode/video.svg',
        'flv': '/icon/iconSystem/vscode/video.svg',
        'webm': '/icon/iconSystem/vscode/video.svg',
        'zip': '/icon/iconSystem/vscode/zip.svg',
        'rar': '/icon/iconSystem/vscode/zip.svg',
        '7z': '/icon/iconSystem/vscode/zip.svg',
        'tar': '/icon/iconSystem/vscode/zip.svg',
        'gz': '/icon/iconSystem/vscode/zip.svg',
        'bz2': '/icon/iconSystem/vscode/zip.svg',
        'xz': '/icon/iconSystem/vscode/zip.svg',
        'exe': '/icon/iconSystem/vscode/default.svg',
        'msi': '/icon/iconSystem/vscode/default.svg',
        'deb': '/icon/iconSystem/vscode/default.svg',
        'rpm': '/icon/iconSystem/vscode/default.svg',
        'dmg': '/icon/iconSystem/vscode/default.svg',
        'pkg': '/icon/iconSystem/vscode/default.svg',
        'appimage': '/icon/iconSystem/vscode/default.svg',
        'snap': '/icon/iconSystem/vscode/default.svg',
        'flatpak': '/icon/iconSystem/vscode/default.svg',
        'iso': '/icon/iconSystem/vscode/default.svg',
        'img': '/icon/iconSystem/vscode/default.svg',
        'vhd': '/icon/iconSystem/vscode/default.svg',
        'vmdk': '/icon/iconSystem/vscode/default.svg',
        'ova': '/icon/iconSystem/vscode/default.svg',
        'ovf': '/icon/iconSystem/vscode/default.svg',
        'cert': '/icon/iconSystem/vscode/certificate.svg',
        'crt': '/icon/iconSystem/vscode/certificate.svg',
        'key': '/icon/iconSystem/vscode/certificate.svg',
        'pem': '/icon/iconSystem/vscode/certificate.svg',
        'p12': '/icon/iconSystem/vscode/certificate.svg',
        'pfx': '/icon/iconSystem/vscode/certificate.svg',
        'crl': '/icon/iconSystem/vscode/certificate.svg',
        'der': '/icon/iconSystem/vscode/certificate.svg',
        'csr': '/icon/iconSystem/vscode/certificate.svg',
        'pub': '/icon/iconSystem/vscode/certificate.svg',
        'sig': '/icon/iconSystem/vscode/certificate.svg',
        'asc': '/icon/iconSystem/vscode/certificate.svg',
        'gpg': '/icon/iconSystem/vscode/certificate.svg',
        'license': '/icon/iconSystem/vscode/license.svg',
        'licence': '/icon/iconSystem/vscode/license.svg',
        'copying': '/icon/iconSystem/vscode/license.svg',
        'unlicense': '/icon/iconSystem/vscode/license.svg',
        'mit': '/icon/iconSystem/vscode/license.svg',
        'gpl': '/icon/iconSystem/vscode/license.svg',
        'apache': '/icon/iconSystem/vscode/license.svg',
        'bsd': '/icon/iconSystem/vscode/license.svg',
        'mpl': '/icon/iconSystem/vscode/license.svg',
        'lgpl': '/icon/iconSystem/vscode/license.svg',
        'agpl': '/icon/iconSystem/vscode/license.svg',
        'epl': '/icon/iconSystem/vscode/license.svg',
        'afl': '/icon/iconSystem/vscode/license.svg',
        'cc0': '/icon/iconSystem/vscode/license.svg',
        'ccby': '/icon/iconSystem/vscode/license.svg',
        'ccbysa': '/icon/iconSystem/vscode/license.svg',
        'ccbynd': '/icon/iconSystem/vscode/license.svg',
        'ccbync': '/icon/iconSystem/vscode/license.svg',
        'ccbyncsa': '/icon/iconSystem/vscode/license.svg',
        'ccbyncnd': '/icon/iconSystem/vscode/license.svg',
        'gfdl': '/icon/iconSystem/vscode/license.svg',
        'odbl': '/icon/iconSystem/vscode/license.svg',
        'ofl': '/icon/iconSystem/vscode/license.svg',
        'osl': '/icon/iconSystem/vscode/license.svg',
        'postgresql': '/icon/iconSystem/vscode/db.svg',
        'mysql': '/icon/iconSystem/vscode/db.svg',
        'sqlite': '/icon/iconSystem/vscode/db.svg',
        'mongodb': '/icon/iconSystem/vscode/db.svg',
        'redis': '/icon/iconSystem/vscode/db.svg',
        'elasticsearch': '/icon/iconSystem/vscode/db.svg',
        'kibana': '/icon/iconSystem/vscode/db.svg',
        'logstash': '/icon/iconSystem/vscode/db.svg',
        'grafana': '/icon/iconSystem/vscode/db.svg',
        'prometheus': '/icon/iconSystem/vscode/db.svg',
        'kubernetes': '/icon/iconSystem/vscode/kubernetes.svg',
        'docker': '/icon/iconSystem/vscode/docker.svg',
        'terraform': '/icon/iconSystem/vscode/terraform.svg',
        'ansible': '/icon/iconSystem/vscode/ansible.svg',
        'puppet': '/icon/iconSystem/vscode/puppet.svg',
        'chef': '/icon/iconSystem/vscode/chef.svg',
        'vagrant': '/icon/iconSystem/vscode/vagrant.svg',
        'jenkins': '/icon/iconSystem/vscode/jenkins.svg',
        'gitlab': '/icon/iconSystem/vscode/gitlab.svg',
        'github': '/icon/iconSystem/vscode/github.svg',
        'bitbucket': '/icon/iconSystem/vscode/bitbucket.svg',
        'azure': '/icon/iconSystem/vscode/azure.svg',
        'aws': '/icon/iconSystem/vscode/aws.svg',
        'gcp': '/icon/iconSystem/vscode/google.svg',
        'firebase': '/icon/iconSystem/vscode/firebase.svg',
        'heroku': '/icon/iconSystem/vscode/heroku.svg',
        'netlify': '/icon/iconSystem/vscode/netlify.svg',
        'vercel': '/icon/iconSystem/vscode/vercel.svg',
        'railway': '/icon/iconSystem/vscode/railway.svg',
        'render': '/icon/iconSystem/vscode/render.svg',
        'digitalocean': '/icon/iconSystem/vscode/digitalocean.svg',
        'cloudflare': '/icon/iconSystem/vscode/cloudflare.svg',
        'nginx': '/icon/iconSystem/vscode/nginx.svg',
        'caddy': '/icon/iconSystem/vscode/caddy.svg',
        'traefik': '/icon/iconSystem/vscode/traefik.svg',
        'haproxy': '/icon/iconSystem/vscode/haproxy.svg',
        'envoy': '/icon/iconSystem/vscode/envoy.svg',
        'istio': '/icon/iconSystem/vscode/istio.svg',
        'linkerd': '/icon/iconSystem/vscode/linkerd.svg',
        'consul': '/icon/iconSystem/vscode/consul.svg',
        'vault': '/icon/iconSystem/vscode/vault.svg',
        'nomad': '/icon/iconSystem/vscode/nomad.svg',
        'etcd': '/icon/iconSystem/vscode/etcd.svg',
        'zookeeper': '/icon/iconSystem/vscode/zookeeper.svg',
        'kafka': '/icon/iconSystem/vscode/kafka.svg',
        'rabbitmq': '/icon/iconSystem/vscode/rabbitmq.svg',
        'nats': '/icon/iconSystem/vscode/nats.svg',
        'pulsar': '/icon/iconSystem/vscode/pulsar.svg',
        'activemq': '/icon/iconSystem/vscode/activemq.svg',
        'zeromq': '/icon/iconSystem/vscode/zeromq.svg',
        'mosquitto': '/icon/iconSystem/vscode/mosquitto.svg',
        'emqx': '/icon/iconSystem/vscode/emqx.svg',
        'hivemq': '/icon/iconSystem/vscode/hivemq.svg',
        'vernemq': '/icon/iconSystem/vscode/vernemq.svg',
        'solace': '/icon/iconSystem/vscode/solace.svg',
        'tibco': '/icon/iconSystem/vscode/tibco.svg',
        'ibmmq': '/icon/iconSystem/vscode/ibmmq.svg',
        'graphql': '/icon/iconSystem/vscode/graphql.svg',
        'protobuf': '/icon/iconSystem/vscode/protobuf.svg',
        'thrift': '/icon/iconSystem/vscode/thrift.svg',
        'avro': '/icon/iconSystem/vscode/avro.svg',
        'openapi': '/icon/iconSystem/vscode/openapi.svg',
        'swagger': '/icon/iconSystem/vscode/swagger.svg',
        'raml': '/icon/iconSystem/vscode/raml.svg',
        'api': '/icon/iconSystem/vscode/api.svg',
        'postman': '/icon/iconSystem/vscode/postman.svg',
        'insomnia': '/icon/iconSystem/vscode/insomnia.svg',
        'hoppscotch': '/icon/iconSystem/vscode/hoppscotch.svg',
        'soapui': '/icon/iconSystem/vscode/soapui.svg',
        'jmeter': '/icon/iconSystem/vscode/jmeter.svg',
        'k6': '/icon/iconSystem/vscode/k6.svg',
        'artillery': '/icon/iconSystem/vscode/artillery.svg',
        'locust': '/icon/iconSystem/vscode/locust.svg',
        'gatling': '/icon/iconSystem/vscode/gatling.svg',
        'tsung': '/icon/iconSystem/vscode/tsung.svg',
        'wrk': '/icon/iconSystem/vscode/wrk.svg',
        'hey': '/icon/iconSystem/vscode/hey.svg',
        'ab': '/icon/iconSystem/vscode/ab.svg',
        'siege': '/icon/iconSystem/vscode/siege.svg',
        'beeswithmachineguns': '/icon/iconSystem/vscode/beeswithmachineguns.svg',
        'boom': '/icon/iconSystem/vscode/boom.svg',
        'autocannon': '/icon/iconSystem/vscode/autocannon.svg',
        'bombardier': '/icon/iconSystem/vscode/bombardier.svg',
        'vegeta': '/icon/iconSystem/vscode/vegeta.svg',
        'fortio': '/icon/iconSystem/vscode/fortio.svg',
        'wrk2': '/icon/iconSystem/vscode/wrk2.svg',
        'oha': '/icon/iconSystem/vscode/oha.svg',
        'httpie': '/icon/iconSystem/vscode/httpie.svg',
        'curl': '/icon/iconSystem/vscode/curl.svg',
        'wget': '/icon/iconSystem/vscode/wget.svg',
        'aria2': '/icon/iconSystem/vscode/aria2.svg',
        'youtube-dl': '/icon/iconSystem/vscode/youtube-dl.svg',
        'yt-dlp': '/icon/iconSystem/vscode/yt-dlp.svg',
        'gallery-dl': '/icon/iconSystem/vscode/gallery-dl.svg',
        'instaloader': '/icon/iconSystem/vscode/instaloader.svg',
        'twitter-dl': '/icon/iconSystem/vscode/twitter-dl.svg',
        'reddit-dl': '/icon/iconSystem/vscode/reddit-dl.svg',
        'instagram-dl': '/icon/iconSystem/vscode/instagram-dl.svg',
        'tiktok-dl': '/icon/iconSystem/vscode/tiktok-dl.svg',
        'spotify-dl': '/icon/iconSystem/vscode/spotify-dl.svg',
        'soundcloud-dl': '/icon/iconSystem/vscode/soundcloud-dl.svg',
        'bandcamp-dl': '/icon/iconSystem/vscode/bandcamp-dl.svg',
        'mixcloud-dl': '/icon/iconSystem/vscode/mixcloud-dl.svg',
        'twitch-dl': '/icon/iconSystem/vscode/twitch-dl.svg',
        'vimeo-dl': '/icon/iconSystem/vscode/vimeo-dl.svg',
        'dailymotion-dl': '/icon/iconSystem/vscode/dailymotion-dl.svg',
        'bilibili-dl': '/icon/iconSystem/vscode/bilibili-dl.svg',
        'youku-dl': '/icon/iconSystem/vscode/youku-dl.svg',
        'iqiyi-dl': '/icon/iconSystem/vscode/iqiyi-dl.svg',
        'tudou-dl': '/icon/iconSystem/vscode/tudou-dl.svg',
        'letv-dl': '/icon/iconSystem/vscode/letv-dl.svg',
        'sohu-dl': '/icon/iconSystem/vscode/sohu-dl.svg',
        'qq-dl': '/icon/iconSystem/vscode/qq-dl.svg',
        '163-dl': '/icon/iconSystem/vscode/163-dl.svg',
        '56-dl': '/icon/iconSystem/vscode/56-dl.svg',
        'kugou-dl': '/icon/iconSystem/vscode/kugou-dl.svg',
        'kuwo-dl': '/icon/iconSystem/vscode/kuwo-dl.svg',
        '9ku-dl': '/icon/iconSystem/vscode/9ku-dl.svg',
        '1ting-dl': '/icon/iconSystem/vscode/1ting-dl.svg',
        'migu-dl': '/icon/iconSystem/vscode/migu-dl.svg',
        'joox-dl': '/icon/iconSystem/vscode/joox-dl.svg',
        'qqmusic-dl': '/icon/iconSystem/vscode/qqmusic-dl.svg',
        'netease-dl': '/icon/iconSystem/vscode/netease-dl.svg',
        'xiami-dl': '/icon/iconSystem/vscode/xiami-dl.svg',
        'baidu-dl': '/icon/iconSystem/vscode/baidu-dl.svg',
        'google-dl': '/icon/iconSystem/vscode/google-dl.svg',
        'bing-dl': '/icon/iconSystem/vscode/bing-dl.svg',
        'yahoo-dl': '/icon/iconSystem/vscode/yahoo-dl.svg',
        'duckduckgo-dl': '/icon/iconSystem/vscode/duckduckgo-dl.svg',
        'sogou-dl': '/icon/iconSystem/vscode/sogou-dl.svg',
        '360-dl': '/icon/iconSystem/vscode/360-dl.svg',
        'startpage-dl': '/icon/iconSystem/vscode/startpage-dl.svg',
        'yandex-dl': '/icon/iconSystem/vscode/yandex-dl.svg',
        'naver-dl': '/icon/iconSystem/vscode/naver-dl.svg',
        'daum-dl': '/icon/iconSystem/vscode/daum-dl.svg',
        'nate-dl': '/icon/iconSystem/vscode/nate-dl.svg',
        'zum-dl': '/icon/iconSystem/vscode/zum-dl.svg',
        'eniro-dl': '/icon/iconSystem/vscode/eniro-dl.svg',
        'ekolay-dl': '/icon/iconSystem/vscode/ekolay-dl.svg',
        'yam-dl': '/icon/iconSystem/vscode/yam-dl.svg',
        'mod': '/icon/iconSystem/vscode/config.svg',
        'gui': '/icon/iconSystem/vscode/config.svg',
        'event': '/icon/iconSystem/vscode/default.svg',
        'focus': '/icon/iconSystem/vscode/default.svg',
        'idea': '/icon/iconSystem/vscode/default.svg',
        'on_action': '/icon/iconSystem/vscode/default.svg',
        'decision': '/icon/iconSystem/vscode/default.svg',
        'default': '/icon/iconSystem/material/document.svg'
      }
    }
  },
  {
    id: 'minimal',
    name: '简洁风格',
    description: '简单几何形状，减少视觉干扰',
    type: 'emoji',
    icons: {
      folder: {
        closed: '▶',
        open: '▼'
      },
      files: {
        'json': '◻',
        'js': '◼',
        'ts': '◼',
        'vue': '●',
        'css': '▲',
        'scss': '▲',
        'sass': '▲',
        'less': '▲',
        'png': '◇',
        'jpg': '◇',
        'jpeg': '◇',
        'gif': '◇',
        'svg': '◇',
        'txt': '◻',
        'md': '◻',
        'mod': '⚙',
        'gui': '▣',
        'event': '○',
        'focus': '◎',
        'idea': '◉',
        'on_action': '⚡',
        'decision': '⚡',
        'default': '◻'
      }
    }
  }
]

// 当前图标集ID
const currentIconSetId = ref('emoji')

// 图标面板可见性
const iconPanelVisible = ref(false)

/**
 * 获取当前图标集
 */
const currentIconSet = computed(() => {
  return iconSets.find(set => set.id === currentIconSetId.value) || iconSets[0]
})

/**
 * 获取文件图标
 */
export function getFileIcon(fileName: string, isDirectory = false, isExpanded = false): { type: 'emoji' | 'svg', content: string } {
  const iconSet = currentIconSet.value
  
  if (isDirectory) {
    const iconPath = isExpanded ? iconSet.icons.folder.open : iconSet.icons.folder.closed
    return {
      type: iconSet.type,
      content: iconPath
    }
  }
  
  // 获取文件扩展名
  const ext = fileName.split('.').pop()?.toLowerCase()
  if (!ext) {
    return {
      type: iconSet.type,
      content: iconSet.icons.files.default
    }
  }
  
  // 返回对应扩展名的图标，如果没有则返回默认图标
  const iconPath = iconSet.icons.files[ext] || iconSet.icons.files.default
  return {
    type: iconSet.type,
    content: iconPath
  }
}

/**
 * 设置图标集
 */
async function setIconSet(iconSetId: string, saveToSettings = true) {
  const iconSet = iconSets.find(set => set.id === iconSetId)
  if (!iconSet) return
  
  currentIconSetId.value = iconSetId
  
  // 保存到设置
  if (saveToSettings) {
    try {
      const result = await loadSettings()
      if (result.success && result.data) {
        const settings = result.data as Record<string, unknown>
        settings.iconSet = iconSetId
        await saveSettings(settings)
      }
    } catch (error) {
      console.error('保存图标设置失败:', error)
    }
  }
}

/**
 * 从设置加载图标集
 */
async function loadIconSetFromSettings(settings?: Record<string, unknown>) {
  try {
    const loadedSettings = settings ?? await (async () => {
      const result = await loadSettings()
      if (!result.success || !result.data) return null
      return result.data as Record<string, unknown>
    })()

    if (loadedSettings) {
      const savedIconSet = loadedSettings.iconSet as string
      if (savedIconSet && iconSets.some(set => set.id === savedIconSet)) {
        currentIconSetId.value = savedIconSet
      } else {
        // 默认图标集
        currentIconSetId.value = 'emoji'
      }
    } else {
      currentIconSetId.value = 'emoji'
    }
  } catch (error) {
    console.error('加载图标设置失败:', error)
    currentIconSetId.value = 'emoji'
  }
}

/**
 * 切换图标面板可见性
 */
function toggleIconPanel() {
  iconPanelVisible.value = !iconPanelVisible.value
}

/**
 * 关闭图标面板
 */
function closeIconPanel() {
  iconPanelVisible.value = false
}

/**
 * 文件树图标系统 Composable
 */
export function useFileTreeIcons() {
  return {
    iconSets,
    currentIconSetId,
    currentIconSet,
    iconPanelVisible,
    setIconSet,
    loadIconSetFromSettings,
    toggleIconPanel,
    closeIconPanel,
    getFileIcon
  }
}
